### ISSUE TITLE
建议在http://xxx.xxx.xxx/cached-scripts 的页面添加一个搜索的功能

### ISSUE THREAD

**Issue by siburuxue** [PeeHaa/OpCacheGUI#103]
[https://lh3.googleusercontent.com/5RbCGuY53U7-0JBB8fGQ0SiIqxG0f4XFdfFKAtOsZMWgbGdo0KGYqCvJdCMREb87D5iZMrwZj9iVzrnmYKudlOmgYZRbE-_XN7e2pTH3u9VJPNmuAvgiElnPjqz3-OZc67Lf61-6-7i7rjifQSAQkdr0yDF0PUfNnFa-T_-xJYrcitN1QLcvNVbkK_DeGs810hwV5NZaDZ3C9nfyi4FfROtCu7eAHNZOUL1GHF4Gc2mX8NDN-5Brc-pAGOsHiam2VjgsbgC_zzXC4njWwqFRX53lUkeno-DmgQH8-7VUoEVGSWiQlvvf1wZF6nMz8fMb0KNG0Bl290FzO9DsFn90NNSfNXWHgIiRadpFxY79OXLifu1jfkN2TlE0KdMkC1QE_iCnGLxs6cFMQ6Z2tNFStrlilwP9gNqyLM-5Z2-QbY4-cuv8IY2-tHiRHId0g9n3sTjpUqM6j-fscQ80DePnWb9565506xhdHBHKpJDoGkLueAfZXr7p9I3iio6OEy-e0eO1qm9cBYonSoWdzRWdpp0spMw6kZIB6lOrWPJhZpjKUNBX3IeSAayh-s_oiS33ptTIUevZ8LNKXeeI_tQ4FNKKfOZnMf4ozFXha5E=w3360-h1878](url)

**Comment by JimChenWYU** [comment]
兄弟，在路由`/cached-scripts`下，点击OVERVIEW，搜索框就会出现了。

**Comment by siburuxue** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    最好默认出现 我还在页面上重新写了这个功能。。。。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                siburuxue
                            
                    
                        
                            
                                    siburuxue@aliyun.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年03月24日 23:21，Jim Chen<notifications@github.com> 写道： 


兄弟，在路由/cached-scripts下，点击OVERVIEW，搜索框就会出现了。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
