### ISSUE TITLE
Fatal error of  v1.0.1

### ISSUE THREAD

**Issue by ed29** [PeeHaa/OpCacheGUI#105]
Fatal error: Cannot use variable $request twice in /var/ed29.com/OpCacheGUI-1.0.1/routes.php on line 13

**Comment by dant89** [comment]
Looks like this was fixed? https://github.com/PeeHaa/OpCacheGUI/commit/c27d321c6d09d94eea12cb291c11f88ae818f7da

**Comment by ed29** [comment]
I see,thank you.
By the way,i can't login via www,here is the user section of init.example.php

$login = [
    'username'  => 'peehaa',
    'password'  => '',
    'whitelist' => [
        '*',
    ],
];

The login button is gray,what is wrong?
