### ISSUE TITLE
Call to undefined function OpCacheGUI\\Security\\random_bytes() on PHP 5.6

### ISSUE THREAD

**Issue by ravhirizaldi** [PeeHaa/OpCacheGUI#107]
Trying to access the application on PHP 5.6 but only show text like "Status, Enabled, Cache Full, etc".
Here's my config :

```
return [
    'username'        => '',
    'password'        => '',
    'whitelist'       => [
        '172.20.30.*',
		'172.10.10.*',
		'localhost'
    ],
    'language'        => 'en',
    'timezone'        => 'Asia/Jakarta',
    'error_reporting' => E_ALL,
    'display_errors'  => 'On',
    'log_errors'      => 'On',
    'uri_scheme'      => Router::QUERY_STRING
];
```

This is the log from httpd : 

```[Sun Jun 20 21:19:48.497785 2021] [:error] [pid 22472] [client 172.10.10.20:59491] PHP Fatal error:  Call to undefined function OpCacheGUI\\Security\\random_bytes() in /var/www/html/OpCacheGUI/src/OpCacheGUI/Security/CsrfToken.php on line 82```

Is I'am missing something? This app run perfectly on PHP 7.4.

**Comment by Erwane** [comment]
Master branch is for php 7
For php5.6 use this commit : https://github.com/PeeHaa/OpCacheGUI/tree/bf8451f7e3246bb095aef0620531fe55d438481c
and tarball : https://github.com/PeeHaa/OpCacheGUI/archive/bf8451f7e3246bb095aef0620531fe55d438481c.tar.gz

**Comment by ekinhbayar** [comment]
Correct. The minimum php version is ^7 in composer.json, closing this as it has been answered.
