### ISSUE TITLE
APCu statistics

### ISSUE THREAD

**Issue by amenadiel** [PeeHaa/OpCacheGUI#24]
This one is on the edge of being off topic, but several developers that used APC until php 5.4 are now using a combination of OpCache + [APCu](https://github.com/krakjoe/apcu) for user variables. 

@PeeHaa, what do you think about the idea of adding an APCu tab, displayed only if  `extension_loaded('apcu')` is true? I could start experimenting with styles to match your GUI look & feel.

**Comment by Kofl** [comment]
Not sure, if I should open up a seperate ticket, but just tried the latest versionand "APCU status" gives the following error message:

Catchable fatal error: Argument 3 passed to OpCacheGUI\APCu\Status::__construct() must implement interface OpCacheGUI\I18n\Translator, array given, called in /cluster/public_html/OpCacheGUI-apcu/template/apcustatus.phtml on line 3 and defined in /cluster/public_html/OpCacheGUI-apcu/src/OpCacheGUI/APCu/Status.php on line 72

I am using php-5.6.5

**Comment by PeeHaa** [comment]
Yeah working out the last issues in the apcu branch before I can release the feature. Currently the apcu branch is a WIP

**Comment by Kofl** [comment]
Thanks for the unbelieveable fast feedback and again for the great work on OpenCacheGUI.

**Comment by PeeHaa** [comment]
Np. Thanks for the kind words.

**Comment by WebEndevSnippets** [comment]
The ACPu piece would be awesome. Any timeline on releasing it?
Thanks for your work. Very nice GUI!

**Comment by PeeHaa** [comment]
@WebEndevSnippets Most of the work is already done in the [apcu branch](https://github.com/PeeHaa/OpCacheGUI/tree/apcu). IIRC only need to clean something up and adds nice looking graphs for fragmentation.

Once I have closed the [roadmap](https://github.com/PeeHaa/OpCacheGUI/issues/55#issuecomment-67734727) I will have a better idea of a timeframe for you all
