### ISSUE TITLE
deactivate user authentication

### ISSUE THREAD

**Issue by tessus** [PeeHaa/OpCacheGUI#61]
I understand that user authentication is important.

However, it is rather annoying and useless, if you are running this web app via a reverse proxy already protected by Apache authentication.
There should be a way to deactivate user authentication, similar to deactivating the whitelist.

P.S.: Btw, great GUI, nice features, great app.

**Comment by PeeHaa** [comment]
@tessus If you [clear the username in the init file](https://github.com/PeeHaa/OpCacheGUI/blob/master/init.example.php#L64) (e.g. empty string or `null`) you should bypass user authentication.

https://github.com/PeeHaa/OpCacheGUI/blob/master/src/OpCacheGUI/Auth/User.php#L69

**Comment by tessus** [comment]
Ah, perfect, thanks. I removed the entire stanza and got an error. Stupid me, I could have thought of trying to set it to an empty string.
Thanks again.
