### ISSUE TITLE
Make OpCacheGUI compatible to PHP 5.4

### ISSUE THREAD

**Issue by casterx** [PeeHaa/OpCacheGUI#62]
Hi, 

AFAIK, OpCacheGUI is only compatible to PHP 5.5+ because of password_hash() right? In that case, could we use https://github.com/ircmaxell/password_compat to make it compatible to PHP 5.4?

It's great to have it for PHP 5.4 :)

Thanks

**Comment by PeeHaa** [comment]
passhash was not the original reason for targeting 5.5. 5.5 was the first release that officially shipped with opcache. 5.4 had the PECL ZendOpcache / optimizer. I am not 100% sure whether the API is 1:1 the same.

If this is the case I am willing to see whether I can easily enable 5.4 support.

**Comment by Quix0r** [comment]
PHP 5.4 has reached EOL: http://php.net/supported-versions.php Means, no security updates and such. You should (generally a good idea) upgrade your code to latest PHP 7 stable release as also 5.5 is EOL and 5.6 will see the same fade.

So the best choice is to close this issue as invalid and set required PHP version to 5.6 or even 7.0. Please note that 5.6 is now only receiving security updates and only until end of 2018.

**Comment by doeess** [comment]
PHP 5.4 is the only version available and supported on RedHat Enterprise 7. We are obliged to use this version currently. There are additional licenses that allow for other versions but natively 5.4 is all that's allowed. RedHat provides security updates as required.

**Comment by PeeHaa** [comment]
5.4 passes on travis (see [the 5.4 branch](https://github.com/PeeHaa/OpCacheGUI/tree/php-5.4)). 

No idea whether it actually work with that version of the Zend Optimizer.

If it doesn't work the chance that I will make time to actually dive into it are slim :P 

As @Quix0r said. 5.4 is dead and rhel sucks for shipping ancient packages like that.

i will release a new version soon or you can grab the last version from the 5.4 branch yourself. *fingers crossed*

**Comment by Quix0r** [comment]
@doeess No offense here. :-) Maybe consider switching to other distribution (with updated PHP packages) or upgrade the RHEL to a newer version. 7.x gives you so much benefits, like reduced memory fingerprint, 3-4 times faster processing (PHP instructions) and much more (like Zend's OpCache is now fully part of PHP).
