### ISSUE TITLE
Timezone setting does not seem to have an effect

### ISSUE THREAD

**Issue by CommanderBond** [PeeHaa/OpCacheGUI#63]
Hi,

on my Windows server, OpCacheGUI's default timezone (that fits to mine) is not correctly displayed in the report. Report shows UTC times. I tried to set it to Europe/Vienna or Europe/London in init.production.php, but it does not have an effect (other configuration changes in ths file have an effect!).

I was previously using opcache.php by Rasmus Lerdorf that correctly shows time values based on UTC+2.

What's wrong here?

**Comment by PeeHaa** [comment]
I *think* this is a bug. Will investigate.

**Comment by ymchun** [comment]
PHP ignore timezone when giving an integer timestamp to DateTime object

**Comment by kondrich** [comment]
Indeed,

correct times are displayed after changing
'start_time'           => (new \DateTime('@' . $stats['start_time']))->format('H:i:s d-m-Y'),
to
'start_time'           => (new \DateTime())->setTimestamp($stats['start_time'])->format('H:i:s d-m-Y'),
in src/OpCacheGUI/OpCache/Status.php

In the same file I changed 
$lastRestartTime = (new \DateTime('@' . $stats['last_restart_time']))->format('H:i:s d-m-Y');
to
$lastRestartTime = (new \DateTime())->setTimestamp($stats['last_restart_time'])->format('H:i:s d-m-Y');
as well to display correct timestamp for restarts, too.

Thanks ymchun

**Comment by PeeHaa** [comment]
Tnx @ymchun 

will go through the code to fix it in a later release.

**Comment by CommanderBond** [comment]
Btw, timestamp calculation for files in cache is missing timezone calculation, too:
In the same file from above I changed 
```php
$timestamp = (new \DateTime('@' . $script['timestamp']))->format('H:i:s d-m-Y');
```
to
```php
$timestamp = (new \DateTime())->setTimestamp($script['timestamp'])->format('d.m.Y H:i:s');
```
and
```php
'last_used_timestamp' => (new \DateTime('@' . $script['last_used_timestamp']))->format('H:i:s d-m-Y'),
```
to
```php
'last_used_timestamp' => (new \DateTime())->setTimestamp($script['last_used_timestamp'])->format('d.m.Y H:i:s'),
```

**Comment by blueJack92** [comment]
I have this bug, too. Please fix it! Thank you very much for this great OpCache-GUI!

**Comment by PeeHaa** [comment]
Fixed it master.

Sorry for letting you wait two years+ :-(

💓
