### ISSUE TITLE
Rewrite rule for Apache as provided in docs not working

### ISSUE THREAD

**Issue by jbenoit2011** [PeeHaa/OpCacheGUI#64]
Hello,

I setup OpCacheGUI in a separate vhost and so I use the [vhost example](https://github.com/PeeHaa/OpCacheGUI/wiki/Installation#under-a-dedicated-subdomain) provided in docs.
But the RewriteRule did not worked, Apache sent me a 400 error each time I tried to access to the GUI.

So I search in the closed issues, and I found in [this one](https://github.com/PeeHaa/OpCacheGUI/issues/2#issuecomment-22079390) that @PeeHaa gave another version of the rewrite rule. This one works perfectly.

So am I the only one who encounter issues with the RewriteRule provided in docs ?
If yes, may I suggest a PR to update the documentation ?

**Comment by isbkch** [comment]
Thank you, came here for this.

**Comment by kingfisher64** [comment]
Oh thanks jbenoit2011 that info was so so useful.

Perhaps this could be added to the readme file?

Thanks PeeHaa

**Comment by pdanysz** [comment]
I prefer use this .htaccess, is work perfect for me :)

`RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
`

**Comment by PeeHaa** [comment]
Updated the wiki installation page https://github.com/PeeHaa/OpCacheGUI/wiki/Installation
