### ISSUE TITLE
Status icons all green

### ISSUE THREAD

**Issue by pmaselkowski** [PeeHaa/OpCacheGUI#65]
Hi!

I've upgraded OpCacheGui to latest version (tried 1.0.1 and dev), and all of:

```
Enabled 
Cache full  
Restart pending 
Restart in progress 
```

Have green indicators, while only `Enabled` should be green, as others are fine.

**Comment by lourdas** [comment]
The same here, using 1.0.1. But from my perspective, I don't see anything wrong with it. The cache full with red indicator could mean that the cache **is** full, with the red indicator showing an issue. So, the way I set it, the green indicator means that everything is fine and not otherwise.

**Comment by pmaselkowski** [comment]
I looked for this status colors as for checkboxes. Green = true, red = false. It works like that on configuration page. I mean that it's inconsistent with config page.
So one could read it as as:
```
Enabled = true
Cache full  = true
Restart pending = true
Restart in progress = true
```
Especially that enabled has same status as full.
