### ISSUE TITLE
Can't Login even with blank username and password

### ISSUE THREAD

**Issue by xycofryx** [PeeHaa/OpCacheGUI#66]
I just finished installing your software, now i can't login :(

**Comment by PeeHaa** [comment]
Related: https://github.com/PeeHaa/OpCacheGUI/issues/61 ?

**Comment by mombrea** [comment]
@xycofryx Don't forget to edit the IP whitelist as well if you're not on localhost. This is the wide open configuration:

$login = [
    'username'  => '',
    'password' => '',
    'whitelist' => [
        '*',
    ],
];

**Comment by xycofryx** [comment]
Sorry for the late reply.  It's still a problem. I can't login even with if I cleared it and put a wildcard in the white-list. I also tried the hashing my password to no avail.
