### ISSUE TITLE
login from cached_scripts page

### ISSUE THREAD

**Issue by bkdotcom** [PeeHaa/OpCacheGUI#68]
config:

`$uriScheme = Router::QUERY_STRING;`

if my session times out, I'll be on the url /OpCacheGUI/?cached-scripts
and presented with the login form

The form will post to 
/OpCacheGUI/?cached-scripts  and fails to log me in

I'm required to change the url to /OpCacheGUI/   to relogin

**Comment by Jlaird** [comment]
I am also having this same issue.

**Comment by PeeHaa** [comment]
This is fixed on master https://github.com/PeeHaa/OpCacheGUI/commit/ebfac169789bae5a64ee95ee7fc5e4e542735b6a.

There is another issue with logins unrelated to above which I will fix.
