### ISSUE TITLE
Configuration Page Notice with PHP7 for opcache.load_comments

### ISSUE THREAD

**Issue by tmannherz** [PeeHaa/OpCacheGUI#69]
The configuration directive `opcache.load_comments` has been removed in PHP 7. 

On the OpCache Configuration page, the following notice is generated:

`Notice: Undefined index: opcache.load_comments in opcache/src/OpCacheGUI/OpCache/Configuration.php on line 82`

http://git.php.net/?p=php-src.git;a=commitdiff;h=0a21a0c752a06d25704e04c15464700f75164849

**Comment by lexa-uw** [comment]
+1

**Comment by vredeling** [comment]
indeed: http://php.net/ChangeLog-7.php
I've created a pull request to resolve the issue: https://github.com/PeeHaa/OpCacheGUI/pull/74

**Comment by ekinhbayar** [comment]
Closing as #74 is merged, thanks!
