### ISSUE TITLE
Could you improve a bit on the documentation for installing

### ISSUE THREAD

**Issue by cAstraea** [PeeHaa/OpCacheGUI#72]
Something is amiss with the paths and maybe I'm not bright enough to figure out how to install this. Been trying for almost 2 minutes I'm about to give up. 
http://prnt.sc/agqfiz

**Comment by vredeling** [comment]
I get the same problem with the paths. If I use `$uriScheme = Router::QUERY_STRING;` in my init file, the router paths seem to work.

**Comment by luispabon** [comment]
As a composer-installed project, it's impossible to modify the config files since they're hardcoded to be looked for only on OpCacheGui's folder.

**Comment by PeeHaa** [comment]
This issue seems to be related with not having correctly set up the rewriting. For more information see the [Setting up the webserver](https://github.com/PeeHaa/OpCacheGUI/wiki/Installation#setting-up-the-webserver) part of the installation guide.
