### ISSUE TITLE
Login with credentials error

### ISSUE THREAD

**Issue by mtx-z** [PeeHaa/OpCacheGUI#73]
Hi ! I just installed this pretty cool GUI. 

My only problem is with the login, wich seems broken.

1/ Clearing all user/password -> site still ask for login
2/ creation a password with a php script using password_hash("mypass", PASSWORD_DEFAULT); and setting this value, the login always fail
3/ only way to access is to add my IP into the white list

Anyone succed to implement the login ? (I'm on QUERY_STRING mode)

Thx !!

**Comment by hanxue** [comment]
Clearing the user/password works for me. I got tripped when I created `init.production.php`, and realize by default `init.example.php` is used. Either change the settings in `init.example.php` or change `init.deployment.php` to require your updated init file.

**Comment by otsuarez** [comment]
Hi @mtx-z 
could you please try using single quotes instead? like this:
password_hash('mypass', PASSWORD_DEFAULT); 
I had the same problem (user/pass not working, ip whitelist yes) and that solved it.
btw, `php -a` is a friend ;)

**Comment by Theolodewijk** [comment]
same issue

**Comment by delphiprogramming** [comment]
I have same problem

**Comment by pdanysz** [comment]
I believe that problem can occur if whitelist is wrong set.
I use this:

`$login = [
    'username'  => 'opuser',
    'password'  => 'oppassword',
    'whitelist' => ['*']
];`

**Comment by never615** [comment]
same issue

**Comment by PeeHaa** [comment]
I went through the login logic again and fixed some issues.

If people still have a problem feel free to open a nice issue and I will have another look.
