### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by visages** [PeeHaa/OpCacheGUI#77]
Thank you for this amazing tool. 
I 'm sorry, I'm misunderstanding the correct way to implement it.
I'm running it on _Debian 8.6 + nginx + Ispconfig_
Let's say my website root is located at `/var/www/websiteRoot/web`
Where shall I put your script folder ? And where shall I put `init.production.php` ?

I 've been trying several configurations, it seems I'm missing something obvious !
I'll be really grateful if you can spend a minute of your time to comment that point.

Thanks a lot,
best regards.

**Comment by PeeHaa** [comment]
In the new version (master branch) we have a new way to handle config files. Please consult [our wiki](https://github.com/PeeHaa/OpCacheGUI/wiki/Installation#setting-up-the-project) for more info.
