### ISSUE TITLE
No password_hash function to encrypt password in request

### ISSUE THREAD

**Issue by ushell** [PeeHaa/OpCacheGUI#79]
1.load configure password  in index.php
2.get password in routes.php (no encrypt)
3.login function in Auth\User.php use hash_verify() to compare user raw input, but this password is not encrypt! How to use password_verify to compare different strings?

**Comment by PeeHaa** [comment]
Generate the password hash locally using `password_hash('yourpassword', PASSWORD_DEFAULT, ['cost' => 14]);`.

Or use [my site](https://passhash.pieterhordijk.com) if you really have to. Note that the information submitted (the password) is being send to me server.
