### ISSUE TITLE
PHP 7 mcrypt_create_iv() is deprecated

### ISSUE THREAD

**Issue by Eiskaltereistee** [PeeHaa/OpCacheGUI#81]
Hi,

for PHP 7.1.3 I got the following error:
Deprecated: Function mcrypt_create_iv() is deprecated in /var/www/opcache.sergo.local/OpCacheGUI/src/OpCacheGUI/Security/Generator/Mcrypt.php 

Is there anybody who has is fixed the file already? Or can I simple change mcrypt to openssl functions?

Thanks!

**Comment by AJMaxwell** [comment]
You can switch to openssl functions or use `random_bytes()` as the PHP Manual [suggests](http://php.net/manual/en/function.mcrypt-create-iv.php).

**Comment by PeeHaa** [comment]
This has been fixed in master https://github.com/PeeHaa/OpCacheGUI/commit/3f8005d28db95d6c7fc87d2339dc64dbdcd9f70e
