### ISSUE TITLE
Call to undefined function OpCacheGUI\Security\random_bytes()

### ISSUE THREAD

**Issue by krnan9525** [PeeHaa/OpCacheGUI#95]
I have both php5 and 7 installed.
Run php -v , shows:
PHP 7.1.10-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:33:22) ( NTS )

This is the error I got: 

<div id="login">
    <form method="post" action="/">
        <input type="hidden" name="csrfToken" value="<br />
<b>Fatal error</b>:  Call to undefined function OpCacheGUI\Security\random_bytes() in <b>/var/www/html/OpCacheGUI/src/OpCacheGUI/Security/CsrfToken.php</b> on line <b>82</b><br />

**Comment by PeeHaa** [comment]
I think you dropped part of your issue somehow at the end :-)

**Comment by krnan9525** [comment]
<div id="login">
    <form method="post" action="/">
        <input type="" name="csrfToken" value="<br />
<b>Fatal error</b>:  Call to undefined function OpCacheGUI\Security\random_bytes() in <b>/var/www/html/OpCacheGUI/src/OpCacheGUI/Security/CsrfToken.php</b> on line <b>82</b><br />

**Comment by krnan9525** [comment]
Call to undefined function OpCacheGUI\Security\random_bytes() in <b>/var/www/html/OpCacheGUI/src/OpCacheGUI/Security/CsrfToken.php</b> on line <b>82

**Comment by krnan9525** [comment]
Github wrapped the HTML code...

**Comment by PeeHaa** [comment]
Just to double check. You only get that error on a 5.4 PHP build right?

**Comment by krnan9525** [comment]
I pulled it from master

**Comment by krnan9525** [comment]
OK. I pulled it from v2.0.0 branch and the error is gone.

Grand

**Comment by PeeHaa** [comment]
What version of PHP are you running the web interface on?

**Comment by krnan9525** [comment]
Suppose to be 7.1. 
It solved for the moment.

Cheers

**Comment by krnan9525** [comment]
I can't log in from the homepage. 
Even if I leave the username and password as blank. 
It will always take me back to login page again

**Comment by PeeHaa** [comment]
There has been several fixes for this. For PHP 7+ use the master branch. For PHP < 7 use the 5.4 branch.
